#!/usr/bin/env python3

"""
# sends bereal notification using ntfy.sh
"""

import requests
from datetime import datetime
from dateutil import tz
import logging
from os import getenv, path

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

API_KEY = getenv("BEREAL_API_KEY")
URL = f"https://bereal.devin.rest/v1/moments/latest?api_key={API_KEY}"


def get_local_notification_time(timestamp: int, current_zone):
    utc_zone = tz.gettz("UTC")
    utc = datetime.fromtimestamp(timestamp, utc_zone)
    return utc.astimezone(current_zone)

def is_push_required(timestamp: int, timezone: str = "Europe/Dublin"):
    current_zone = tz.gettz(timezone)
    now = datetime.now(current_zone)
    return get_local_notification_time(timestamp, current_zone).date() == now.date() and not path.isfile("/tmp/bereal_indicator.txt")

def push_notification():
    with open ("/tmp/bereal_indicator.txt", "xt") as f:
        f.write("notification_sent")

    data = {
        "topic": getenv("NTFY_TOPIC"),
        "tags": ["tada"],
        "message": "BeReal has triggered",
        "title": "Time to BeReal",
        "priority": 5,
    }
    requests.post("https://ntfy.sh", json=data)

def main():
    response = requests.get(url=URL).json()
    if is_push_required(timestamp=response["regions"]["europe-west"]["ts"]):
        logger.info("Pushing notification")
        push_notification()
    else:
        logger.info("Notification not required")

if __name__ == "__main__":
    main()
