#!/usr/bin/env sh

# notify when device is logged into via ssh
set -o errexit
set -o nounset
IFS=

if [ "${PAM_TYPE}" = "open_session" ]; then
	curl \
		-H prio:high \
		-H tags:warning \
		-d "SSH login: ${PAM_USER} from ${PAM_RHOST}" \
		ntfy.sh/$NTFY_TOPIC
fi
