#!/usr/bin/env sh

# manager for vim sessions
set -euo pipefail
IFS=$'\n\t'

suffix='.vim'
# Flags
list_directory=false

while getopts 'r:l' c; do
	case $c in
	r) remove_session=$OPTARG ;;
	l) list_directory=true ;;
	*) echo "Invalid option" && exit ;;
	esac
done
shift "$((OPTIND - 1))"

if $list_directory; then
	ls "$SESSIONS"
fi

if [ ! -z "$remove_session" ]; then
	read -p "Are you sure you want to remove $SESSIONS/$remove_session ? " -n 1 -r
	echo
	if [[ $reply =~ ^[Yy]$ ]]; then
		rm $SESSIONS/$remove_session$suffix && echo "> $remove_session deleted."
	fi
fi

if [ ! -z $* ]; then
	nvim -S $sessions/$*$suffix
fi
