#!/usr/bin/env sh

# cleanup all docker containers, images, volumes, networks
set -eu
IFS=$'\n\t'

# Stop all containers
docker stop `docker ps -qa`
# Remove all containers
docker rm `docker ps -qa`
# Remove all images
docker rmi -f `docker images -qa `
# Remove all volumes
docker volume rm $(docker volume ls -qf)
# Remove all networks
docker network rm `docker network ls -q`
