#!/usr/bin/env sh

# Open remote repo for current git repository.

# Original written by rajitbanerjee
set -eu

remote="$(git config remote.origin.url)"
remote_type="$(printf '%s' "$remote" | cut -c -5)"
if [ X"$remote_type" = X"https" ]; then
	repo="$remote"
elif util-contains "$remote" "@"; then
	repo="https://$(printf "%s" "$remote" | cut -d "@" -f 2 | tr ":" "/")"
else
	repo="https://code.amazon.com/packages/$(printf "%s" "$remote" | cut -d "/" -f 5)"
fi

echo "$repo"
util-copy "$repo"
util-open "$repo"
