#!/usr/bin/env sh

# generic reminder
#
# Requires zsh compatibility. Writes reminder messages to $messages_directory that are 'cat'ted before each shell. Must be run with REMINDER, PERIOD and REMINDER TEXT variables defined.
set -o errexit
IFS=
	
message_and_exit() {
	echo "$REMINDER_TEXT" > "$REMINDER_MESSAGES/$REMINDER"
	exit
}

run_indicator="$REMINDER_INDICATORS/$REMINDER"

mkdir -p "$REMINDER_MESSAGES"
mkdir -p "$REMINDER_INDICATORS"

if [ ! -f "$run_indicator" ]; then
	message_and_exit
fi

# in seconds
last_modified_time=$(date +%s -r $run_indicator)
current_time=$(date +%s)
elapsed_time=$((current_time - last_modified_time))

if [ "$elapsed_time" -ge "$PERIOD" ]; then
	message_and_exit
fi


rm "$REMINDER_MESSAGES/$REMINDER" 2> /dev/null
exit
