#!/usr/bin/env sh

# commit submodules so that main repo points to current head
set -o errexit
set -o nounset

for i in $(git submodule foreach --quiet 'echo $path'); do
  echo "Staging $i"
  git add "$(git rev-parse --show-toplevel)/$i"
done
git commit -m "auto: Update submodules"
