#!/usr/bin/env sh

# Open remote repo for current git repository.

# Original written by rajitbanerjee
set -eu

remote="$(git config remote.origin.url)"
remote_type="$(printf '%s' "$remote" | cut -c -5)"
if [ X"$remote_type" = X"https" ]; then
	repo="$remote"
else
	repo="https://$(printf "%s" "$remote" | cut -d "@" -f 2 | tr ":" "/")"
fi

sd-open "$repo"
