#!/usr/bin/env bash

# backup to b2
set -o errexit
set -o nounset
set -o pipefail
IFS=
	
export BORG_REPO="$HOME/mount"

util-log "mounting encrypted-b2 remote..."
rclone mount -v --daemon --vfs-cache-mode off encrypted-b2:borg "$BORG_REPO"
util-log "mount complete"

util-log "updating borg repo..."
backup-borg 2>&1 | tee /tmp/backup-borg-b2.log
result="$?"
util-emphasise "Update result: $result"

util-log "unmounting remote..."
fusermount -u "$BORG_REPO"
util-log "unmount complete"

exit "$result"
