#!/usr/bin/env sh

# borg backup to external drive
set -o errexit
set -o nounset
IFS=
	

export BORG_REPO=/mnt/userfiles/

if [ ! -d "$BORG_REPO" ]; then
    echo "Directory $BORG_REPO doesn't exist. Check if external drive is mounted." 1>&2
    exit 1
fi

info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

borg create                         \
    --verbose                       \
    --filter AME                    \
    --list                          \
    --stats                         \
    --show-rc                       \
    --compression lz4               \
    --exclude-caches                \
                                    \
    ::'{hostname}-{now}'            \
    /home/conor/docs                \
    /home/conor/media               \

backup_exit=$?

info "Pruning repository"

borg prune                          \
    --list                          \
    --glob-archives '{hostname}-*'  \
    --show-rc                       \
    --keep-weekly   1               \
    --keep-monthly  2               \
    --keep-yearly   6               \
    --save-space                    \

prune_exit=$?

info "Compacting repository"

borg compact

compact_exit=$?

global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))
global_exit=$(( compact_exit > global_exit ? compact_exit : global_exit ))

if [ ${global_exit} -eq 0 ]; then
    info "Backup, Prune, and Compact finished successfully"
elif [ ${global_exit} -eq 1 ]; then
    info "Backup, Prune, and/or Compact finished with warnings"
else
    info "Backup, Prune, and/or Compact finished with errors"
fi

exit ${global_exit}
