#!/usr/bin/env python

# notify with command result using ntfy

# Override success and failure priorities by inline setting env variables
import sys
from os import getenv
from requests import post
from subprocess import run as subprocess_run


SUCCESS_PRIORITY = int(getenv("SUCCESS_PRIORITY", 3))
FAILURE_PRIORITY = int(getenv("FAILURE_PRIORITY", 4))


def _send_notification(command, error):
    url = getenv("NTFY_LINK")

    data = {
        "topic": url,
        "message": f"* {command} * completed with return code {error}",
        "title": "Command success",
        "priority": SUCCESS_PRIORITY,
    }
    if error:
        data["title"] = "Command failure"
        data["priority"] = FAILURE_PRIORITY

    post("https://ntfy.sh", json=data)


def main():
    if not all(1 <= priority <= 5 for priority in [SUCCESS_PRIORITY, FAILURE_PRIORITY]):
        raise ValueError("Priority ranges between 1 (minimum) and 5 (maximum)")

    command = " ".join(sys.argv[1:])
    process = subprocess_run(command, shell=True)
    _send_notification(command, process.returncode)


if __name__ == "__main__":
    main()
