#!/usr/bin/env python

# notify with command result using ntfy
import os
import sys
import subprocess

def _send_notification(command, error):
    url = os.environ["NTFY_LINK"]
    if error:
        json = f'{{"topic": "{url}", "message": "* {command} * completed with return code {error}", "title": "Command failed", "tags": ["failure"], "priority": 4}}'
    else:
        json = f'{{"topic": "{url}", "message": "* {command} * completed successfully", "title": "Command finished", "tags": ["success"], "priority": 3}}'
    os.system(f"curl -d '{json}' ntfy.sh/")


def _run_command(command):
    process = subprocess.run(command, shell=True)
    if process.returncode != 0:
        raise subprocess.CalledProcessError(process.returncode, process.args)


def main():
    command = " ".join(sys.argv[1:])
    try:
        _run_command(command)
        _send_notification(command, 0)
    except subprocess.CalledProcessError as exc:
        _send_notification(command, exc.returncode)


if __name__ == "__main__":
    main()
