#!/usr/bin/env sh

# rename files to lower snake case

# original by rajitbanerjee
set -o errexit
set -o nounset
IFS=

print_help() {
	echo "Rename individual files, or all files in the specified directories, to 
replace spaces with underscores, and convert file name to lower case.
Usage:
1. Rename all files in current directory
    $ ./rename-files ./
2. Rename all files in multiple directories
    $ ./rename-files dir1/ dir2/ dir3/
3. Rename individual files
    $ ./rename-files file1 file2 file3
"
}

if [ $# -eq 0 ]; then
	print_help
	exit 1
fi

for dir in $*; do
	for file in $dir*; do
		if [ -f $file ]; then
			parent="$(dirname $file)"
			new_name="$(echo $(basename $file) | tr '[:upper:]' '[:lower:]' | tr -s ' ' | tr ' ' '_')"
			mv $file "$parent/$new_name"
		fi
	done
done
