#!/usr/bin/env sh

# sets up laptop for when docked
set -eu
IFS=$'\n\t'

echo "Setting monitor layout"
xrandr --output DP1 --left-of eDP1 --mode 2560x1440

echo "Setting up keyboard"
setxkbmap -option "" -v && setxkbmap us

echo "Resetting wallpaper"
wm-wallpaper

echo "Connecting to mouse"
bluetooth connect mxmaster
