#!/usr/bin/env sh

# selects tmux session using fzf or creates one if required
IFS=
	
selected=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | fzf --preview='tmux capture-pane -ep -t {}' --print-query)
selected="${selected##*$'\n'}"

tmux switch-client -t "$selected" &>/dev/null || tmux -f $HOME/.config/tmux/tmux.conf attach -t "$selected"  &>/dev/null || tmux -f $HOME/.config/tmux/tmux.conf attach new -s "$selected"
